# FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu18.04
FROM nvidia/cuda:11.6.0-cudnn8-devel-ubuntu18.04
# FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt-get update && apt-get install -y libboost-all-dev \
                                         libgoogle-perftools-dev

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
RUN conda --version


RUN conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
RUN conda install -c dglteam dgl-cuda11.6
RUN conda install pyg -c pyg
RUN pip install requests

RUN  apt-get update -y
RUN apt-get install -y nsight-compute-2023.1.0

RUN conda init
RUN /bin/bash -c "source root/.bashrc"

WORKDIR /tcgnn

